fieldLayouts:
  ba71c8b2-2a8b-4e74-a9e3-ca18d2c78796:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7084c682-34cc-4dda-9ba3-b6dff3648cc2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d33e7a25-7d24-4730-ae70-ed3b98661adc
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 8bff640d-fb71-4ddb-9041-b9bba82f9343 # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
