defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  bad40dcf-5717-4096-892c-caca8bdb0ef9: # My Site
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
